# Generated by Django 4.2.18 on 2025-01-29 17:40

from django.db import migrations, models
from ..workaround import ReloadModel


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="nick",
            field=models.CharField(default="hey, you!", max_length=255),
        ),
        migrations.AddField(
            model_name="grandchild",
            name="nick",
            field=models.CharField(default="hey, you!", max_length=255),
        ),
        migrations.AddField(
            model_name="grandparent",
            name="nick",
            field=models.CharField(default="hey, you!", max_length=255),
        ),
        migrations.AddField(
            model_name="parent",
            name="nick",
            field=models.CharField(default="hey, you!", max_length=255),
        ),
        # Uncomment this to work around the issue
        # ReloadModel(("db", "child")),
    ]
