# Generated by Django 4.2.18 on 2025-01-29 17:41

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def create_default(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Create the default task_configuration collection."""
    Grandparent = apps.get_model("db", "Grandparent")
    Parent = apps.get_model("db", "Parent")
    Child = apps.get_model("db", "Child")
    Grandchild = apps.get_model("db", "Grandchild")

    gp = Grandparent.objects.create(name="default", nick="default")
    p = Parent.objects.create(name="default", nick="default", parent=gp)
    c = Child.objects.create(name="default", nick="default", parent=p)
    Grandchild.objects.create(name="default", nick="default", parent=c)


def remove_default(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Remove the default taks_configuration collection."""
    Grandparent = apps.get_model("db", "Grandparent")
    Parent = apps.get_model("db", "Parent")
    Child = apps.get_model("db", "Child")
    Grandchild = apps.get_model("db", "Grandchild")

    Grandchild.objects.filter(name="default").delete()
    Child.objects.filter(name="default").delete()
    Parent.objects.filter(name="default").delete()
    Grandparent.objects.filter(name="default").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_models"),
    ]

    operations = [migrations.RunPython(create_default, remove_default)]
